





























# This is a basic workflow to help you get started with Actions

name: v1

# Controls when the workflow will run
on:
  pull_request:
  # Triggers the workflow on push or pull request events but only for the live branch
  push:
    branches: live

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check_remote_download:
    strategy:
      matrix:
        profile:
          - "single"
          - "multi_client"
          - "multi_server"
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout this repo
        uses: actions/checkout@v3
      # Runs a single command using the runners shell
      - name: test installing
        run: |
          echo $GITHUB_WORKSPACE
          ls $GITHUB_WORKSPACE
          (cd servers/v1 &&
          PROFILE="${{ matrix.profile }}" CURSE_API_KEY='${{ secrets.TEST_CURSE_API_KEY }}' ./prepare.sh &&
          ./pack.sh)












































